version: '3.10'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ugragdb
    ports:
      - "5434:5432"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data:/docker-entrypoint-initdb.d
    command: >
      bash -c "apt-get update &&
               apt-get install -y postgresql-15-pgvector &&
               docker-entrypoint.sh postgres"

  opensearch:
    image: opensearchproject/opensearch:2.10.0
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms4g -Xmx4g"
      - "plugins.security.disabled=true"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 6G
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - os_data:/usr/share/opensearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

volumes:
  postgres_data:
  os_data:
